# Import Modules

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

---

# Read CSV

In [2]:
df = pd.read_csv("../csv_files/app_user_behavior_dataset.csv")

df.shape

(50000, 25)

In [3]:
df.head()

,user_id,age,gender,country,device_type,app_version,sessions_per_week,avg_session_duration_min,daily_active_minutes,feature_clicks_per_session,...,days_since_last_login,subscription_type,ads_clicked_last_30_days,content_downloads,social_shares,rating_given,churn_risk_score,engagement_score,account_age_days,marketing_source
0,100000,56,Female,India,iOS,2.1,5,3.41,52.71,13,...,20,Basic,9,5,2,NaN,0.31,55.79,1152,Referral
1,100001,46,Male,UK,iOS,1.0,8,24.44,42.03,7,...,7,Free,8,3,3,3.0,0.87,82.39,1059,Email Campaign
2,100002,32,Female,UK,iOS,1.2,12,5.34,76.69,7,...,33,Free,11,6,1,2.0,0.63,42.49,678,Google Ads
3,100003,25,Male,India,Android,2.0,5,3.98,65.38,16,...,17,Basic,6,3,1,3.0,0.43,62.81,92,Organic
4,100004,38,Male,Australia,Android,1.0,10,12.85,57.06,13,...,21,Basic,4,4,2,5.0,0.43,38.21,772,Email Campaign

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   user_id                        50000 non-null  int64
 1   age                            50000 non-null  int64
 2   gender                         50000 non-null  str
 3   country                        50000 non-null  str
 4   device_type                    50000 non-null  str
 5   app_version                    50000 non-null  float64
 6   sessions_per_week              50000 non-null  int64
 7   avg_session_duration_min       50000 non-null  float64
 8   daily_active_minutes           50000 non-null  float64
 9   feature_clicks_per_session     50000 non-null  int64
 10  notifications_opened_per_week  50000 non-null  int64
 11  in_app_search_count            50000 non-null  int64
 12  pages_viewed_per_session       50000 non-null  int64
 13  crash_events_last_30_days      50000 non-null  int64
 14  support_tickets_raised         50000 non-null  int64
 15  days_since_last_login          50000 non-null  int64
 16  subscription_type              50000 non-null  str
 17  ads_clicked_last_30_days       50000 non-null  int64
 18  content_downloads              50000 non-null  int64
 19  social_shares                  50000 non-null  int64
 20  rating_given                   44978 non-null  float64
 21  churn_risk_score               50000 non-null  float64
 22  engagement_score               50000 non-null  float64
 23  account_age_days               50000 non-null  int64
 24  marketing_source               50000 non-null  str
dtypes: float64(6), int64(14), str(5)
memory usage: 10.9 MB

In [5]:
df.describe()

,user_id,age,app_version,sessions_per_week,avg_session_duration_min,daily_active_minutes,feature_clicks_per_session,notifications_opened_per_week,in_app_search_count,pages_viewed_per_session,crash_events_last_30_days,support_tickets_raised,days_since_last_login,ads_clicked_last_30_days,content_downloads,social_shares,rating_given,churn_risk_score,engagement_score,account_age_days
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,44978.000000,50000.000000,50000.000000,50000.000000
mean,124999.500000,38.513040,1.476126,7.999680,13.149842,45.164537,12.013920,4.99662,3.999060,13.470760,0.397520,0.19666,22.038240,5.995800,3.002260,2.001440,3.630664,0.500834,64.940409,603.785100
std,14433.901067,12.094948,0.470158,2.829438,8.946944,19.505118,3.480289,2.23518,1.997763,6.343635,0.633992,0.44442,12.985237,2.453313,1.731818,1.413435,1.087339,0.288578,14.838827,345.567524
min,100000.000000,18.000000,1.000000,0.000000,0.060000,5.000000,1.000000,0.00000,0.000000,3.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,10.000000,7.000000
25%,112499.750000,28.000000,1.100000,6.000000,6.570000,31.650000,10.000000,3.00000,3.000000,8.000000,0.000000,0.00000,11.000000,4.000000,2.000000,1.000000,3.000000,0.250000,54.900000,302.000000
50%,124999.500000,39.000000,1.200000,8.000000,11.240000,45.210000,12.000000,5.00000,4.000000,13.000000,0.000000,0.00000,22.000000,6.000000,3.000000,2.000000,4.000000,0.500000,65.025000,604.000000
75%,137499.250000,49.000000,2.000000,10.000000,17.570000,58.440000,14.000000,6.00000,5.000000,19.000000,1.000000,0.00000,33.000000,8.000000,4.000000,3.000000,4.000000,0.750000,75.090000,906.000000
max,149999.000000,59.000000,2.100000,26.000000,91.400000,129.130000,28.000000,16.00000,19.000000,24.000000,5.000000,4.00000,44.000000,19.000000,13.000000,11.000000,5.000000,1.000000,100.000000,1199.000000

---

# Splitting Numerical and Categorical Features

In [6]:
numeric_features = []
categorical_features = []

for column in df.columns:
    if df[column].dtype == "str":
        categorical_features.append(column)
    else:
        numeric_features.append(column)

In [7]:
categorical_features

['gender', 'country', 'device_type', 'subscription_type', 'marketing_source']

---

# Data Cleaning

In [8]:
df_copy = df.copy()

## Cleaning - Categorical Fetures

In [9]:
df[categorical_features].info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             50000 non-null  str
 1   country            50000 non-null  str
 2   device_type        50000 non-null  str
 3   subscription_type  50000 non-null  str
 4   marketing_source   50000 non-null  str
dtypes: str(5)
memory usage: 3.3 MB

In [10]:
for column in categorical_features:
    print(df[column].unique())
    print()

<ArrowStringArray>
['Female', 'Male', 'Other']
Length: 3, dtype: str

<ArrowStringArray>
['India', 'UK', 'Australia', 'Germany', 'Singapore', 'Canada', 'USA']
Length: 7, dtype: str

<ArrowStringArray>
['iOS', 'Android', 'Web']
Length: 3, dtype: str

<ArrowStringArray>
['Basic', 'Free', 'Premium']
Length: 3, dtype: str

<ArrowStringArray>
['Referral', 'Email Campaign', 'Google Ads', 'Organic', 'Facebook Ads']
Length: 5, dtype: str

- Since the `categorical` features do not contain any missing values or duplicate values, no data cleaning was required for the categorical features.

---

## Cleaning - Numerical Features

In [11]:
df[numeric_features].describe()

,user_id,age,app_version,sessions_per_week,avg_session_duration_min,daily_active_minutes,feature_clicks_per_session,notifications_opened_per_week,in_app_search_count,pages_viewed_per_session,crash_events_last_30_days,support_tickets_raised,days_since_last_login,ads_clicked_last_30_days,content_downloads,social_shares,rating_given,churn_risk_score,engagement_score,account_age_days
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,44978.000000,50000.000000,50000.000000,50000.000000
mean,124999.500000,38.513040,1.476126,7.999680,13.149842,45.164537,12.013920,4.99662,3.999060,13.470760,0.397520,0.19666,22.038240,5.995800,3.002260,2.001440,3.630664,0.500834,64.940409,603.785100
std,14433.901067,12.094948,0.470158,2.829438,8.946944,19.505118,3.480289,2.23518,1.997763,6.343635,0.633992,0.44442,12.985237,2.453313,1.731818,1.413435,1.087339,0.288578,14.838827,345.567524
min,100000.000000,18.000000,1.000000,0.000000,0.060000,5.000000,1.000000,0.00000,0.000000,3.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,10.000000,7.000000
25%,112499.750000,28.000000,1.100000,6.000000,6.570000,31.650000,10.000000,3.00000,3.000000,8.000000,0.000000,0.00000,11.000000,4.000000,2.000000,1.000000,3.000000,0.250000,54.900000,302.000000
50%,124999.500000,39.000000,1.200000,8.000000,11.240000,45.210000,12.000000,5.00000,4.000000,13.000000,0.000000,0.00000,22.000000,6.000000,3.000000,2.000000,4.000000,0.500000,65.025000,604.000000
75%,137499.250000,49.000000,2.000000,10.000000,17.570000,58.440000,14.000000,6.00000,5.000000,19.000000,1.000000,0.00000,33.000000,8.000000,4.000000,3.000000,4.000000,0.750000,75.090000,906.000000
max,149999.000000,59.000000,2.100000,26.000000,91.400000,129.130000,28.000000,16.00000,19.000000,24.000000,5.000000,4.00000,44.000000,19.000000,13.000000,11.000000,5.000000,1.000000,100.000000,1199.000000

In [12]:
df[numeric_features].isnull().sum()

user_id                             0
age                                 0
app_version                         0
sessions_per_week                   0
avg_session_duration_min            0
daily_active_minutes                0
feature_clicks_per_session          0
notifications_opened_per_week       0
in_app_search_count                 0
pages_viewed_per_session            0
crash_events_last_30_days           0
support_tickets_raised              0
days_since_last_login               0
ads_clicked_last_30_days            0
content_downloads                   0
social_shares                       0
rating_given                     5022
churn_risk_score                    0
engagement_score                    0
account_age_days                    0
dtype: int64

### Null Imputation - `rating_given`

In [13]:
df["rating_given"].value_counts()

rating_given
4.0    17465
3.0    11199
5.0     9911
2.0     3885
1.0     2518
Name: count, dtype: int64

In [14]:
rating_given_mode = df["rating_given"].mode()[0]

df["rating_given"] = df["rating_given"].fillna(rating_given_mode)

- Missing values in the `rating_given` column were filled using the `mode` value.

---

# Storing CSV

In [19]:
df.isnull().sum()

user_id                          0
age                              0
gender                           0
country                          0
device_type                      0
app_version                      0
sessions_per_week                0
avg_session_duration_min         0
daily_active_minutes             0
feature_clicks_per_session       0
notifications_opened_per_week    0
in_app_search_count              0
pages_viewed_per_session         0
crash_events_last_30_days        0
support_tickets_raised           0
days_since_last_login            0
subscription_type                0
ads_clicked_last_30_days         0
content_downloads                0
social_shares                    0
rating_given                     0
churn_risk_score                 0
engagement_score                 0
account_age_days                 0
marketing_source                 0
dtype: int64

In [22]:
df.to_csv("../csv_files/app_user_behavior_cleaned.csv")

---